[build]
  publish = "."

[[redirects]]
  from = "https://funtravel.mymacguy.us/"
  to   = "https://funtravel.mymacguy.us/funtravel/"
  status = 301
  force = true

[[redirects]]
  from = "/product/:id"
  to   = "/funtravel/product.html?id=:id"
  status = 200

[[redirects]]
  from = "/funtravel/product/:id"
  to   = "/funtravel/product.html?id=:id"
  status = 200

[[redirects]]
  from = "/funtravel/shop"
  to   = "/funtravel/shop.html"
  status = 200

[[redirects]]
  from = "/funtravel/about"
  to   = "/funtravel/about.html"
  status = 200

[[redirects]]
  from = "/funtravel/contact"
  to   = "/funtravel/contact.html"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/funtravel/404.html"
  status = 301
